apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      initContainers:
        - name: collectstatic
          image: django-example
          imagePullPolicy: Never
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - secretRef:
                name: django-secrets
            - configMapRef:
                name: django-config
          volumeMounts:
            - name: staticfiles
              mountPath: /static/
              readOnly: false 
      containers:
      - name: django-example
        image: django-example
        imagePullPolicy: Never
        ports:
          - containerPort: 8000
            protocol: TCP
        envFrom:
          - secretRef:
              name: django-secrets
          - configMapRef:
              name: django-config
        volumeMounts:
          - name: staticfiles
            mountPath: /static/ ## where it wants to have the emptyDir mounted
            readOnly: false
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: staticfiles
            mountPath: /static/
            readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: staticfiles
          emptyDir: {} ## we do not supply any further requirements for the emptyDir
